travis:
  secure:
    BINSTAR_TOKEN: ilkjDiR5yh8HWM4wmsgxXJEYeMXvb0JBKk8gkpzF6hef8PkV/dLxCaxdr2r6u732wFR/ZLaGvOFhG7Edw8JHd6rl8v1enw6xxA0l55lzkUuJippBdbvoqK6fpeedCZ2fhEQVVpi1mji/hqT1Gi160soPfEDvukaLYGy0W313WPDUhgsPb4oFZSTR6At+cQauvCLYaD2mjF5gi6nRoCj2Adwb+DPHXnyVh0tOUe+DV5dWR3UQO91ifAIt4L2T4VsUHy9vqvfIYESUvP3FjEmVUkIvtgkBrb0PK/LOoIfjCYyaV1RW82sfnoktThMkch+ysXZ8dB9W7TxN6WbA8IFNuII2V3aUpM+lqxUCMI5efXTqQ8oW79yuohAsQ8CyFm0IpNv95gHi9pnPvKWe3w1izQyn3Yv/OtREJuyWzybM7eidV5mn7T2UI01WKj5Wcs0AHM+PfgBUC3a4q5OMzmX5xtrhp8QwIQouC65ufBd7QNn+XQpvn1+cawYZ9b47YhIaDsN+MBtk7MXmjr0YoHL9WuzghGE2DFEfQ/JI1sW2IGY3r3XDT5y9iylxjA+pLJQf5n0uNb7cOOCUcyK3Pw9HqEcT/USWCXVbwgCs0CO7+9fV+2wCqnw2+vP0olayxmROUKxT9QOGOFrhyB9jR3T+b4EX8Nmqm7HY14DXpjNvTFc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
